/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Froggy.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.head.geometry} material={materials.Frog_material} />
      <mesh geometry={nodes.body.geometry} material={materials.Frog_material} position={[0.02, -1.15, 0]} scale={0.51} />
      <mesh geometry={nodes.shirt.geometry} material={materials.Frog_material} position={[0.02, -1.14, 0]} scale={0.53} />
      {/* <mesh geometry={nodes.Plane.geometry} material={materials.bg} position={[0.03, -2.28, 1.56]} scale={11.54} /> */}
    </group>
  )
}

useGLTF.preload('/Froggy.gltf')
